### ISSUE TITLE
"Cannot set headers..." error intermittently

### ISSUE THREAD

**Issue by getify** [anseki/node-static-alias#2]
I'm seeing this error show up in my log frequently but intermittently (like once every 5-10 requests, about once every 5 minutes or so):

```
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:471:11)
    at ServerResponse.writeHead (_http_server.js:231:21)
    at Server.finish (/tmp/site/node_modules/node-static/lib/node-static.js:125:17)
    at finish (/tmp/site/node_modules/node-static/lib/node-static.js:170:14)
    at /tmp/site/node_modules/node-static/lib/node-static.js:337:13
    at streamFile (/tmp/site/node_modules/node-static/lib/node-static.js:382:13)
    at ReadStream.<anonymous> (/tmp/site/node_modules/node-static/lib/node-static.js:375:17)
    at ReadStream.emit (events.js:182:13)
    at fs.close (fs.js:2161:14)
    at FSReqWrap.oncomplete (fs.js:152:20)
```

I have logged out what URL is being requested that's causing this error, but it's a normal URL that when I try it, it works fine for me, and does **not** cause this error in the log. So it has to be something other than the URL (not sure, maybe some other headers?).

Anyway, my code is very basic... it looks like this:

```js
var nodeStaticAlias = require("node-static-alias");
var staticServer = new nodeStaticAlias.Server(path.join(__dirname,"static"),{
        alias: [
                {
                        match: /[^]/,
                        serve: "index.html",
                },
        ],
});
```

And in my HTTP request handler:

```js
res.setHeader("Strict-Transport-Security","max-age=" + 1E9 + "; includeSubdomains");

// unconditional, permanent HTTPS redirect
if (req.headers["x-forwarded-proto"] !== "https") {
    res.writeHead(301,{
        "Cache-Control": "public, max-age=31536000",
        Expires: new Date(Date.now() + 31536000000).toUTCString(),
        Location: `https://${req.headers["host"]}${req.url}`
    });
    res.end();
}
else if (["GET","HEAD"].includes(req.method)) {
    staticServer.serve(req,res);
}
else {
    res.writeHead(404);
    res.end();
}
```

Any thoughts on how I can track down what's causing this and fix it?

**Comment by anseki** [comment]
Hi @getify, thank you for the report.

It seems that the error message is correct. That is, you can not set the response headers after they are sent.
I tried your code, and that worked fine without an error. However, that handler has problem.
Maybe, you confuse the listener for a request event with the handler for the response.
The `setHeader` method gets an error if it is called after the response was sent. Also, the header can be specified in initialize.

This code works fine:

```js
'use strict';

const
  DOC_ROOT = require('path').join(__dirname, 'static'),
  PORT = 8080,

  fileServer = new (require('node-static-alias')).Server(DOC_ROOT, {
    serverInfo: 'my-server',
    cache: 86400,
    gzip: true,
    headers: {'Strict-Transport-Security': `max-age=${1E9}; includeSubdomains`},
    alias: {
      match: /[^]/,
      serve: 'index.html'
    },
    logger: console
  });

require('http').createServer((request, response) => {
  request.addListener('end', () => {
    if (request.headers['x-forwarded-proto'] !== 'https') {
      const url = `https://${request.headers.host}${request.url}`;
      response.writeHead(301, {
        'Cache-Control': 'public, max-age=31536000',
        Expires: new Date(Date.now() + 31536000000).toUTCString(),
        Location: url
      });
      console.info('REDIRECT: %s', url);
      response.end();
    } else {
      fileServer.serve(request, response, error => {
        if (error) {
          response.writeHead(error.status, error.headers);
          console.error('(%s) %s', request.url, response.statusCode);
          if (error.status === 404) {
            response.end('Not Found');
          }
        } else {
          console.info('(%s) %s', request.url, response.statusCode);
        }
      });
    }
  }).resume();
}).listen(PORT);

console.log(`START: http://localhost:${PORT}/\nROOT: ${DOC_ROOT}`);
console.log('(^C to stop)');
```

**Comment by getify** [comment]
90% (or more) of the requests coming in are NOT causing this error. It's only occasionally that it's happening.

As far as my code is concerned, this error happens strictly after I hand off to node-static-alias, by calling `serve(req,res)`. It's happening entirely inside of there. As you can see, the only header that I set before calling `serve(..)` is the HSTS header, and I HAVE NOT run any other code like `res.writeHead(..)` or anything.

My handler is set up like this:

```js
var httpServer = http.createServer(handleRequest);

function handleRequest(req,res) {
   res.setHeader("Strict-Transport-Security","max-age=" + 1E9 + "; includeSubdomains");

   // unconditional, permanent HTTPS redirect
   if (req.headers["x-forwarded-proto"] !== "https") {
       res.writeHead(301,{
           "Cache-Control": "public, max-age=31536000",
           Expires: new Date(Date.now() + 31536000000).toUTCString(),
           Location: `https://${req.headers["host"]}${req.url}`
       });
       res.end();
   }
   else if (["GET","HEAD"].includes(req.method)) {
       staticServer.serve(req,res);
   }
   else {
       res.writeHead(404);
       res.end();
   }
}
```

That's literally how my code is set up, so there's no other paths where it could be my code sending/flushing headers early or anything. There's something about node-static-alias (or node-static) that's causing this to happen.

**Comment by anseki** [comment]
The `setHeader` method throws an error if it is called after the response was sent.
When the response was failed, the `setHeader` method doesn't throw an error because the response is not sent yet.
To set the `Strict-Transport-Security` header, use `headers` in `Server` constructor instead of `setHeader` method. (See https://github.com/anseki/node-static-alias/issues/2#issuecomment-390852604)
The `x-forwarded-proto:https` header makes the `staticServer.serve` run and the error is thrown. Therefore, your code sets a header after after the response was sent because node-static-alias doesn't set any header.

The code you showed doesn't work. I think your code you didn't show sets a header.

**Comment by getify** [comment]
> The setHeader method throws an error if it is called after the response was sent.

I'm well aware of that. ***My*** call to `setHeader(..)` (for HSTS) is happening first, not *after*. So it's definitely not the culprit. Morever, I've commented that line of code out and the errors still keep happening, so it's not the problem.

> To set the Strict-Transport-Security header, use headers in Server constructor instead of setHeader method.

Whether it's done with `setHeader(..)` or via `headers` in the constructor, or not done at all, the error I'm experiencing keeps happening.

> The x-forwarded-proto:https header makes the staticServer.serve run and the error is thrown. 

I don't have any idea what you mean by this? How does an `if` statement looking at an inbound request header have anything to do with the call to `serve(..)`?

> Therefore, your code sets a header after after the response was sent

Uhhh, I don't see how that's at all possible. Look at the code I provided, the clear flow control is that via the `if` statements, ***either*** `serve(..)` runs or the code block with `res.writeHead(..)` runs, but they do not both run for the same request. That's how `if..else` logic works.

> The code you showed doesn't work.

What do you mean, doesn't work? I literally copy-n-pasted code from my working server file.

> I think your code you didn't show sets a header.

I'm not skipping any relevant code. There's no code that's setting any other headers, and there's no definitely no code that's flushing headers before I hand off to `serve(..)`.

I've already verified via debugging that the error happens inside of the `serve(..)` call, so I'm not sure why you're focused on the code outside of the `serve(..)` call.

------

This code is a full and exact copy of my `server.js` file, with a minimal set of logic in it. It causes the errors I'm seeing.

```js
"use strict";

var path = require("path");
var fs = require("fs");
var http = require("http");
var httpServer = http.createServer(handleRequest);
var nodeStaticAlias = require("node-static-alias");
var staticServer = new nodeStaticAlias.Server(path.join(__dirname,"static"),{
        alias: [
                {
                        match: /[^]/,
                        serve: "index.html",
                },
        ],
});

httpServer.listen(8003);

// *********************

function handleRequest(req,res) {
        // unconditional, permanent HTTPS redirect
        if (req.headers["x-forwarded-proto"] !== "https") {
                res.writeHead(301,{
                        "Cache-Control": "public, max-age=31536000",
                        Expires: new Date(Date.now() + 31536000000).toUTCString(),
                        Location: `https://${req.headers["host"]}${req.url}`
                });
                res.end();
        }
        else if (["GET","HEAD"].includes(req.method)) {
                staticServer.serve(req,res);
        }
        else {
                res.writeHead(404);
                res.end();
        }
}
```

That's not hiding any code. That's all of it. You can clearly see I'm not flushing any headers before calling `serve(..)`.

**Comment by anseki** [comment]
The conceivable causes for that, you specified the listener to the `request` event.
Usually, you should specify the listener to the `end` event of the request because there may be multiple requests per connection.
Your `request` event listener sets the header every time. That might be one connection, that is, your listener might set the header again in one response.
Set that to the `end` event instead of `request` event via `request.addListener('end', listener)`.
See https://github.com/anseki/node-static-alias/issues/2#issuecomment-390852604

**Comment by getify** [comment]
I changed the relevant part of the code to this:

```js
req.addListener("end",function requestEnd(){
     req.removeListener("end",requestEnd);
     res.setHeader("Strict-Transport-Security",`max-age=${1E9}; includeSubdomains`);
     staticServer.serve(req,res);
}).resume();
```

Unfortunately, the error keeps happening, and again, only on this specific request that comes from Slackbot, not on any other requests, which all seem to work fine.

**Comment by anseki** [comment]
BTW, [the code you showed last time](https://github.com/anseki/node-static-alias/issues/2#issuecomment-390976914) does not have `setHeader` method.

**Comment by getify** [comment]
> The stack trace you indicated means that the error was thrown from the out of the serve method.

How do you come to that conclusion? The stack trace talks about node-static, which is only being invoked by the `serve(..)` call.

I already tried putting a `try..catch` around the suspect `setHeader(..) call, and no exception is caught. So I'm almost positive the error is happening inside of the `serve(..)` call, not in my code.

> And, the most important problem is that we can not reproduce your case.

I understand that frustration. I share it. I am not in control of whatever slackbot is trying to hit my server. All I can do is report that it's happening.

I already tried creating a request with those same headers, and everything was fine. So it's something other than their request headers. I dunno anything about how that Slackbot request is being made, only that it specifically is triggering my issue.

> BTW, the code you showed last time does not have setHeader method.

Yes, I removed that call for posting because that call is clearly causing the error, but it doesn't make any sense why. That's my whole issue here. Calling `setHeader(..)` before anything else has happened shouldn't be creating any kind of error or problem, ever. It merely queues up a header to be sent out, it doesn't flush headers It should be entirely safe. The fact that it's not *is the bug*.

If it was my `setHeader(..)` that was actually throwing the error, I would be catching it in a `try..catch`. But it's not. Instead, my `setHeader(..)` creates some state that interferes with how node-static does its header handling. THAT is the bug.

The reason why setting headers in the constructor won't work for me is that I need to be able to conditionally set headers for certain responses. The constructor approach sends all headers on every response.

**Comment by getify** [comment]
BTW, another reason I can't just only set headers in the headers config of the constructor: certain headers have timestamps in them, and those would be calculated at the time the node server starts up, and never be re-calculated. But they actually should be relative to (recalculated at) each request. Otherwise, the longer the server stays alive without a restart, the more inaccurate that header's timestamp would be. :(

My only viable option here is to be able to call setHeader(..) upon each request. That's why I need this problem fixed.

**Comment by anseki** [comment]
I recommended that you make sure the steps to reproduce your case and debug-mode. This is very important in debug, typically.
Anyway, I did that, and I could reproduce your case, and I found the cause of this issue, and I show some solutions.

**REPRODUCE**

Run your code that has `setHeader` method.
And then, run this code:

```js
require('request')({
  url: 'http://localhost:8003/index.html',
  headers: {'x-forwarded-proto': 'https'},
  method: 'HEAD'
}, (error, response, body) => {
  console.log('error:', error);
  console.log('statusCode:', response && response.statusCode);
  console.log('headers:');
  console.log(response && response.headers);
  console.log('body:', body);
});
```

The error "Can't set headers..." should be thrown.

**CAUSE**

When the request is a `HEAD` request, a response body should not be sent but your code send that via `serve` method.
And node-static send headers and data, and then, it tries to send headers again in `finish` method when the request is a `HEAD` request.

Actually, the second sending is ignored, and it works without an error.
However, your code calls the `setHeader` method when the request is a `HEAD` request also, it makes a `headers` object. The `response` calls the `setHeader` method if it has `headers` object when the `writeHead` method is called. Therefore, the second `setHeader` calling (i.e. the second sending headers) makes the `setHeader` method throw the error.

**SOLUTIONS**

- Deny a `HEAD` request. This is most easy way, maybe.
```js
} else if (req.method === 'GET') {
  staticServer.serve(req, res);
} else if (req.method === 'HEAD') {
  res.writeHead(403);
  res.end();
} else {
  res.writeHead(404);
  res.end();
}
```

- Set the header only when the request is a `GET` request. You might think that the HSTS header is not needed for `HEAD` request.
```js
if (req.method === 'GET') {
  res.setHeader("Strict-Transport-Security","max-age=" + 1E9 + "; includeSubdomains");
}
```

- Replace `HEAD` with `GET`. A response body is ignored. This avoids the second `writeHead` method calling.
```js
if (req.method === 'HEAD') {
  req.method = 'GET';
}
```

- Specify the constructor option that get a value dynamically. You can specify this if you want to specify dynamically value such as a timestamp.
```js
new nodeStaticAlias.Server(path.join(__dirname,"static"),{
  headers: {
    'X-WhatTime': {toString: () => `It is ${(new Date()).toLocaleTimeString()} now.`}
  }
})
```
The string like "It is 12:07:00 now." is set for `X-WhatTime` header when each response is made.

- And others... e.g. remove `headers` object, make a response without node-static when the request is a `HEAD` request, etc.

The best way in these I think is the constructor option.

**Comment by anseki** [comment]
I would be happy if I could help you. :smile:

The root of the problem I think is that the node-static tries to send headers twice, and node-request (i.e. request module of Node.js) checks that headers were already sent only in `setHeader` method.
That is, the error is thrown only when `setHeader` method was called. If `setHeader` method was not called, the error is not thrown even if `writeHead` method is called again.

As I said, I think that the best way is the constructor option that get a value dynamically via `toString`, at the moment.

When I have time, I will report these to repositories of node-static and Node.js, maybe.

**Comment by getify** [comment]
> When I have time, I will report these to repositories of node-static and Node.js, maybe.

The node-static folks are definitely looking into it here: https://github.com/cloudhead/node-static/issues/207

> As I said, I think that the best way is the constructor option that get a value dynamically via toString, at the moment.

That might work in this particular case, but in general I need to be able to conditionally set headers in some cases and not in others. For example, in one of my other servers, I need to send CORS headers to authorize cross-domain access of certain files, but not send them for all files.

**Comment by anseki** [comment]
I see.
This issue is relevant to two bugs, the bug of node-static and the bug of Node.js.
Since I reported to each repository, those will be fixed. I hope so.

The bug of Node.js hides the bug of node-static.
Therefore, when the bug of node-static is fixed, I think that your code works fine even if the bug of Node.js is not fixed.

If you can't wait for the fixing, try to replace `HEAD` with `GET`.
I know, you might think that it is not good way. However, actuality node-static works same with `HEAD` and `GET` request except for the duplicate calling. In other words, node-static never check the request method except for the duplicate calling. 
https://github.com/cloudhead/node-static/blob/e994d29d620d0dc67cb1e23da764dbddbdd14059/lib/node-static.js#L124

**Comment by anseki** [comment]
Oh sorry, I had forgotten.
node-static works same with HEAD and GET request but Node.js does not.
The request body should be removed.

Hmm...
That might be not good way.

**Comment by anseki** [comment]
If you can't wait for the fixing node-static, try this.

```js
require('http').createServer((request, response) => {

  response.on('pipe', () => {
    if (response._header) {
      response.writeHead = () => { console.warn('Duplicated writeHead was skipped.'); };
    }
  });

  request.addListener('end', () => {

    response.setHeader('foo', 'bar');
    fileServer.serve(request, response);

  }).resume();
}).listen(8080);
```

This just only ignores calling `writeHead` after that was called once.
This code calls `setHeader` method, but an error is not thrown.

**Comment by getify** [comment]
Thanks for the suggestion. I'll look into it.
